//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GazeToolBar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GazeToolBar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_down {
            get {
                object obj = ResourceManager.GetObject("button_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_left {
            get {
                object obj = ResourceManager.GetObject("button_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_right {
            get {
                object obj = ResourceManager.GetObject("button_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_up {
            get {
                object obj = ResourceManager.GetObject("button_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_1 {
            get {
                object obj = ResourceManager.GetObject("crosshair_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_2 {
            get {
                object obj = ResourceManager.GetObject("crosshair_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_3 {
            get {
                object obj = ResourceManager.GetObject("crosshair_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_4 {
            get {
                object obj = ResourceManager.GetObject("crosshair_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_5 {
            get {
                object obj = ResourceManager.GetObject("crosshair_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_6 {
            get {
                object obj = ResourceManager.GetObject("crosshair_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_7 {
            get {
                object obj = ResourceManager.GetObject("crosshair_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshair_None {
            get {
                object obj = ResourceManager.GetObject("crosshair_None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Double_Click_icon {
            get {
                object obj = ResourceManager.GetObject("Double_Click_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Drag_and_drop_icon {
            get {
                object obj = ResourceManager.GetObject("Drag_and_drop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keyboard_icon {
            get {
                object obj = ResourceManager.GetObject("Keyboard_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;abc&quot;
        ///&quot;q&quot;,&quot;Q&quot;
        ///&quot;w&quot;, &quot;W&quot;
        ///&quot;e&quot;, &quot;E&quot;
        ///&quot;r&quot;, &quot;R&quot;
        ///&quot;t&quot;, &quot;T&quot;
        ///&quot;y&quot;, &quot;Y&quot;
        ///&quot;u&quot;, &quot;U&quot;
        ///&quot;i&quot;, &quot;I&quot;
        ///&quot;o&quot;, &quot;O&quot;
        ///&quot;p&quot;, &quot;P&quot;
        ///&quot;a&quot;, &quot;A&quot;
        ///&quot;s&quot;, &quot;S&quot;
        ///&quot;d&quot;, &quot;D&quot;
        ///&quot;f&quot;, &quot;F&quot;
        ///&quot;g&quot;, &quot;G&quot;
        ///&quot;h&quot;, &quot;H&quot;
        ///&quot;j&quot;, &quot;J&quot;
        ///&quot;k&quot;, &quot;K&quot;
        ///&quot;l&quot;, &quot;L&quot;
        ///&quot;z&quot;, &quot;Z&quot;
        ///&quot;x&quot;, &quot;X&quot;
        ///&quot;c&quot;, &quot;C&quot;
        ///&quot;v&quot;, &quot;V&quot;
        ///&quot;b&quot;, &quot;B&quot;
        ///&quot;n&quot;, &quot;N&quot;
        ///&quot;m&quot;, &quot;M&quot;.
        /// </summary>
        internal static string KeyboardSetOne {
            get {
                return ResourceManager.GetString("KeyboardSetOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to àbç
        ///à,À
        ///á,Á
        ///â,Â
        ///ã,Ã
        ///ä,Ä
        ///ç,Ç
        ///è,È
        ///é,É
        ///ê,Ê
        ///ë,Ë
        ///ì,Ì
        ///í,Í
        ///î,Î
        ///ï,Ï
        ///ñ,Ñ
        ///ò,Ò
        ///ó,Ó
        ///ô,Ô
        ///õ,Õ
        ///ö,Ö
        ///ù,Ú
        ///ú,Û
        ///ü,Ü
        ///û,Ù
        ///¿,¿
        ///¡,¡.
        /// </summary>
        internal static string KeyboardSetThree {
            get {
                return ResourceManager.GetString("KeyboardSetThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;123&quot;
        ///&quot;1&quot; , &quot;{F1}&quot;
        ///&quot;2&quot;, &quot;{F2}&quot;
        ///&quot;3&quot;, &quot;{F3}&quot;
        ///&quot;4&quot;, &quot;{F4}&quot;
        ///&quot;5&quot;, &quot;{F5}&quot;
        ///&quot;6&quot;, &quot;{F6}&quot;
        ///&quot;7&quot;, &quot;{F7}&quot;
        ///&quot;8&quot;, &quot;{F8}&quot;
        ///&quot;9&quot;, &quot;{F9}&quot;
        ///&quot;0&quot;, &quot;{F10}&quot;
        ///&quot;@&quot;, &quot;{F11}&quot;
        ///&quot;#&quot;, &quot;{F12}&quot;
        ///&quot;$&quot;, &quot;{HOME}&quot;
        ///&quot;?&quot;, &quot;{END}&quot;
        ///&quot;{(}&quot;, &quot;{PRTSC}&quot;
        ///&quot;{)}&quot;, &quot;{UP}&quot;
        ///&quot;&apos;&quot;, &quot;{%}&quot;
        ///&quot;\&quot;&quot;, &quot;{{}&quot;
        ///&quot;!&quot;, &quot;{}}&quot;
        ///&quot;-&quot;, &quot;/&quot;
        ///&quot;{+}&quot;, &quot;[&quot;
        ///&quot;=&quot;, &quot;]&quot;
        ///&quot;&lt;&quot;, &quot;{LEFT}&quot;
        ///&quot;&gt;&quot;, &quot;{DOWN}&quot;
        ///&quot;;&quot;, &quot;{RIGHT}&quot;
        ///&quot;:&quot;, &quot;&amp;&quot;.
        /// </summary>
        internal static string KeyboardSetTwo {
            get {
                return ResourceManager.GetString("KeyboardSetTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Left_Click_icon {
            get {
                object obj = ResourceManager.GetObject("Left_Click_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mic_icon {
            get {
                object obj = ResourceManager.GetObject("Mic-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Right_Click_icon {
            get {
                object obj = ResourceManager.GetObject("Right_Click_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scroll_icon {
            get {
                object obj = ResourceManager.GetObject("Scroll_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
